---

name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Go test
      run: |
        # we run vet in another step
        go test -vet=off -timeout=1m ./...
        # -race can easily make the crypto stuff 10x slower
        go test -vet=off -timeout=15m -race ./...
    - name: Go analyze
      run: |
        diff -u <(echo -n) <(gofmt -s -d $(git ls-files '*.go'))
        go vet ./...
        curl -L https://github.com/dominikh/go-tools/releases/download/2020.1.5/staticcheck_linux_amd64.tar.gz | tar -xzf -
        ./staticcheck/staticcheck ./...